EnableInfinityTs for encoding / decoding infinity to got time.Time type
jackc/pgx pull request #1615
Opened 2023-05-19 10:09 UTC by bastianrob

This PR resolves https://github.com/jackc/pgx/issues/1574

Implemented only to TimestampCodec, TimestamptzCodec already handles infinity value

Changes:
- `pgtype.Map.EnableInfinityTs`

2023-05-19 10:09 UTC, bastianrob commented on pgtype/builtin_wrappers.go
> +func (w *timeWrapper) ScanTimestamp(v Timestamp, infinityTsEnabled bool) error {
pass down infinityTsEnabled from codec

2023-05-20 13:46 UTC, jackc requested changes
The are a few issues that need to be resolved before this can be merged. A few are inline with the code and the broader ones are mentioned here.

First, I don't understand:

> Implemented only to TimestampCodec, TimestamptzCodec already handles infinity value

I don't see any code in `TimestamptzCodec` that handles this mapping of infinite values to normal time.Time.

Whatever is done should be done for both.

Second, I don't think the `Map` should have the `EnableInfinityTs` method. The `Map` type does not know anything about any `Codec` implementations. It only works in terms of the `Codec` interface. This violates that boundary. Instead, I would suggest the user of this feature call `Map.RegisterType` with the properly configured `Timestamp(tz)Codec`.

 Next, do the values that `Infinity` and `-Infinity` are mapped to need to be configurable? I would have expected them to be hard-coded to the largest and smallest possible `time.Time`s.

The `TimestampScanner` interface can't be changed without breaking backwards compatibility. These conversions will actually have to occur in the `Codec`s and/or `ScanPlan`s and `EncodePlan`s.

Lastly, I think we should find a better name for the whole feature than `EnableInfinityTs`. That name makes sense in lib/pq where `Infinity` wasn't supported at all. But `Infinity` is already supported in pgx because it defines its own types instead of using `time.Time`. This feature is clamping / converting values to fit in `time.Time`. I would expect the feature / flag to be named something like `(Clamp|Convert|Map)Infinity...`

2023-05-20 13:46 UTC, jackc commented on pgtype/timestamp.go
> +	ScanTimestamp(v Timestamp, infinityTsEnabled bool) error
This would be a breaking change. We can't do that in a without a major release.

2023-05-20 13:46 UTC, jackc commented on pgtype/timestamp.go
> +}
In might be more efficient to store a pointer to the `Codec` rather than duplicate these fields.

2023-05-20 13:46 UTC, jackc commented on pgtype/pgtype.go
> +	tsc, _ := ts.Codec.(*TimestampCodec)
This would panic if a different `Codec` was registered.

2025-01-13 10:18 UTC, rubiagatra commented
Hi, @bastianrob do you still want to continue the PR or want to close it?

2025-01-20 14:10 UTC, closed without merging