remove keepalive (since go 1.13 default is 15s)
jackc/pgx pull request #1992
Opened 2024-04-18 09:19 UTC by h0nIg

remove keepalive (since go 1.13 default is 15s). 5 minute for initial keepalive checks are way to high, we should orient us here according to go defaults

https://www.reddit.com/r/golang/comments/d7v7dn/psa_go_113_introduces_15_sec_server_tcp/

2024-04-18 16:51 UTC, paudley commented
This may make sense for TCP connections in general, but it probably doesn't for PostgreSQL connections, where the setup and teardown are expensive enough to want longer keep-alives.

2024-04-23 16:26 UTC, paudley commented
> @paudley "paudley reacted with thumbs down emoji" why?

Sorry, was a mistake!  (undone)   I'm doing some testing on the effects of shorter keepalives in our environments but I don't have results yet.

2024-05-09 21:08 UTC, jackc commented
That keep alive value goes all the way back to b46ee0a9512cb0a375e3bcd0c4fbc6c05bdf3843 in 2014. At the time Go did not have TCP keepalive enabled by default.

If a change is to be made here, I believe the correct change would be to remove the 5 minute value and actually use the Go default rather than hard code it to the current Go default.

2024-05-10 13:25 UTC, h0nIg commented
@jackc done

2024-05-10 15:23 UTC, jackc commented on pgconn/config.go
> +	return &net.Dialer
That's not valid syntax.

2024-05-15 13:40 UTC, jackc requested changes

2024-05-15 13:40 UTC, jackc commented on pgconn/config.go
> +	return net.Dialer
This still doesn't compile. Please try running the tests locally.

2024-05-21 15:37 UTC, merged